version: "3.8"
services:
  app:
    image: ghcr.io/otomay/repomancer:latest
    container_name: repomancer
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=xxx
      - OPENAI_MODEL=gpt-4o-mini # gpt >4 recommended because of the maximum token length.
      - OPENAI_API_PARAMS= # Optional -> Use to pass additional parameters to the OpenAI API client
      - EXPOSE_BACKEND=false # Optional -> Use to expose the backend post route (/api/analyze). Useful for scripts with loop and schedulling.
      - UVICORN_WORKERS=1 # Optional -> Use to set the concurrency level of the Uvicorn server
